import { arrayToLua } from "../lib/util";

export const EntityGetIsAlive = () => true;
export const DoesWorldExistAt = () => true;
export const GameSetFogOfWar = () => true;
export const EntityGetTransform = () => [0, 0, 0, 1, 1];
export const GetSurfaceNormal = () => [false, 0, 0, 0];
export const EntityGetClosestWormAttractor = () => [0, 0, 0];
export const EntityGetClosestWormDetractor = () => [0, 0, 0, 0];
export const GameGetCameraBounds = () => [0, 0, 1, 1];
export const EntityGetWithTag = () => arrayToLua([0]);

export const GuiCreate = () => {};
export const GuiImageButton = () => [false, false];
export const GuiButton = () => [false, false];
export const GuiGetPreviousWidgetInfo = () => [false, false, false, 0, 0, 1, 1, 0, 0, 1, 1];

export const GameIsModeFullyDeterministic = () => true;
export const GameIsBetaBuild = () => false;
export const DebugGetIsDevBuild = () => false;
export const ModGetAPIVersion = () => 6942;

export const ComponentGetValue2 = (id: number, key: string) => 0;

export const $blankFunctions = [
  { // zero
    fn: () => 0,
    list: [
      "PhysicsBodyIDGetGravityScale",
      "InputGetJoystickAnalogButton",
      "GameGetFogOfWar",
      "GameGetFogOfWarBilinear",
      "GameGetSkyVisibility",
      "ComponentGetValueInt",
      "ComponentGetValueFloat",
      "EntityLoad",
      "EntityLoadEndGameItem",
      "EntityCreateNew",
      "EntityAddComponent",
      "EntityGetParent",
      "EntityGetRootEntity",
      "EntityGetClosest",
      "EntityGetClosestWithTag",
      "EntityGetWithName",
      "EntitiesGetMaxID",
      "EntityAddComponent2",
      "ComponentGetVectorSize",
      "ComponentGetEntity",
      "GetUpdatedEntityID",
      "GetUpdatedComponentID",
      "SpawnStash",
      "RemoveMaterialInventoryMaterial",
      "GetMaterialInventoryMainMaterial",
      "GameGetWorldStateEntity",
      "GameGetPlayerStatsEntity",
      "GameGetOrbCountAllTime",
      "GameGetOrbCountThisRun",
      "CellFactory_GetType",
      "EntityGetWandCapacity",
      "GameGetGameEffect",
      "GameGetGameEffectCount",
      "LoadGameEffectEntityTo",
      "GameGetPotionColorUint",
      "StringToHerdId",
      "GetHerdRelation",
      "EntityGetHerdRelation",
      "EntityGetHerdRelationSafe",
      "CreateItemActionEntity",
      "BiomeMapGetVerticalPositionInsideBiome",
      "PhysicsAddBodyImage",
      "PhysicsAddBodyCreateBox",
      "PhysicsAddJoint",
      "PhysicsGetComponentAngularVelocity",
      "StreamingGetVotingCycleDurationFrames",
      "GuiSlider",
      "GetDailyPracticeRunSeed"
    ]
  },
  { // false
    fn: () => false,
    list: [
      "InputIsJoystickButtonDown",
      "InputIsJoystickButtonJustDown",
      "InputIsJoystickConnected",
      "ComponentGetValueBool",
      "EntityHasTag",
      "GameIsIntroPlaying",
      "ComponentGetIsEnabled",
      "GameGetIsGamepadConnected",
      "GameGetOrbCollectedThisRun",
      "GameGetOrbCollectedAllTime",
      "GameIsInventoryOpen",
      "RemovePixelSceneBackgroundSprite",
      "InputIsKeyDown",
      "InputIsKeyJustDown",
      "InputIsKeyJustUp",
      "InputIsMouseButtonDown",
      "InputIsMouseButtonJustDown",
      "InputIsMouseButtonJustUp",
      "IsPlayer",
      "IsInvisible",
      "GameIsDailyRun",
      "GameIsDailyRunOrDailyPracticeRun",
      "StreamingGetIsConnected",
      "StreamingGetSettingsGhostsNamedAfterViewers",
      "GameGetIsTrailerModeEnabled",
    ]
  },
  { // empty string
    fn: () => "",
    list: [
      "ComponentGetMetaCustom",
      "ComponentObjectGetValue",
      "EntityGetName",
      "ComponentGetTypeName",
      "CellFactory_GetName",
      "CellFactory_GetUIName",
      "HerdIdToString",
      "GetRandomActionWithType",
      "GetRandomAction",
      "BiomeMapGetName",
      "StreamingGetConnectedChannelName",
      "StreamingGetRandomViewerName",
      "GuiTextInput",
      "DebugBiomeMapGetFilename",
    ]
  },
  { // empty table
    fn: () => ({}),
    list: [
      "ModMaterialFilesGet", // TODO

      "PhysicsBodyIDGetFromEntity",
      "PhysicsBodyIDQueryBodies",
      "EntityGetAllComponents",
      "EntityGetInRadius",
      "EntityGetAllChildren",
      "EntityGetInRadiusWithTag",
      "EntityGetComponent",
      "CellFactory_GetAllLiquids",
      "CellFactory_GetAllSands",
      "CellFactory_GetAllGases",
      "CellFactory_GetAllFires",
      "CellFactory_GetAllSolids",
      "CellFactory_HasTag",
      "CellFactory_GetTags",
      "GameGetAllInventoryItems",
      "PolymorphTableGet",
    ]
  },
  { // nil
    fn: () => null,
    list: [
      "GuiTextCentered",
      "GameSetPostFxTextureParameter",
      "GameUnsetPostFxTextureParameter",
      "VerletApplyDirectionalForce",
      "VerletApplyCircularForce",
      "RegisterStreamingEvent",
      "PhysicsBodyIDSetGravityScale",
      "PhysicsBodyIDSetDamping",
      "PhysicsBodyIDApplyTorque",
      "PhysicsBodyIDApplyForce",
      "PhysicsBodyIDApplyLinearImpulse",
      "PhysicsBodyIDSetTransform",
      "PhysicsComponentSetTransform",
      "GenomeSetHerdId",
      "EntityRemoveStainStatusEffect",
      "GameSetPostFxParameter",
      "ModDevGenerateSpriteUVsForDirectory",
      "EntityLoadCameraBound",
      "EntityLoadToEntity",
      "EntitySave",
      "EntityKill",
      "EntityRemoveComponent",
      "EntityGetFirstComponent",
      "EntityGetComponentIncludingDisabled",
      "EntityGetFirstComponentIncludingDisabled",
      "EntitySetTransform",
      "EntityApplyTransform",
      "EntityAddChild",
      "EntityRemoveFromParent",
      "EntitySetComponentsWithTagEnabled",
      "EntitySetComponentIsEnabled",
      "EntitySetName",
      "EntityGetTags",
      "EntityAddTag",
      "EntityRemoveTag",
      "EntityGetFilename",
      "ComponentAddTag",
      "ComponentRemoveTag",
      "ComponentHasTag",
      "ComponentGetTags",
      "ComponentGetValue",
      "ComponentSetValue",
      // "ComponentGetValue2",
      "ComponentSetValue2",
      "ComponentObjectGetValue2",
      "ComponentObjectSetValue2",
      "ComponentGetVectorValue",
      "ComponentGetVector",
      "ComponentGetMembers",
      "ComponentObjectGetMembers",
      "RegisterSpawnFunction",
      "SpawnActionItem",
      "LoadEntityToStash",
      "AddMaterialInventoryMaterial",
      "GameScreenshake",
      "GameOnCompleted",
      "GameGiveAchievement",
      "GameDoEnding2",
      "BiomeMapLoad_KeepPlayer",
      "GameClearOrbsFoundThisRun",
      "GameSetCameraFree",
      "GameRegenItemAction",
      "GameRegenItemActionsInContainer",
      "GameRegenItemActionsInPlayer",
      "GameKillInventoryItem",
      "GamePickUpInventoryItem",
      "GameDropAllItems",
      "GameDropPlayerInventoryItems",
      "GameDestroyInventoryItems",
      "GameTriggerGameOver",
      "LoadPixelScene",
      "LoadBackgroundSprite",
      "RemovePixelSceneBackgroundSprites",
      "GameCreateCosmeticParticle",
      "GameCreateParticle",
      "GameCreateSpriteForXFrames",
      "GameShootProjectile",
      "EntityInflictDamage",
      "EntityIngestMaterial",
      "EntityRemoveIngestionStatusEffect",
      "EntityAddRandomStains",
      "EntitySetDamageFromMaterial",
      "EntityRefreshSprite",
      "GamePlayAnimation",
      "SetPlayerSpawnLocation",
      "UnlockItem",
      "PolymorphTableAddEntity",
      "PolymorphTableRemoveEntity",
      "PolymorphTableSet",
      "SessionNumbersSave",
      "AutosaveDisable",
      "StatsBiomeReset",
      "StatsLogPlayerKill",
      "GameEmitRainParticles",
      "GameCutThroughWorldVertical",
      "PhysicsApplyForce",
      "PhysicsApplyTorque",
      "PhysicsApplyTorqueToComponent",
      "PhysicsApplyForceOnArea",
      "PhysicsRemoveJoints",
      "PhysicsSetStatic",
      "PhysicsBody2InitFromComponents",
      "LooseChunk",
      "GameTriggerMusicEvent",
      "GameTriggerMusicCue",
      "GameTriggerMusicFadeOutAndDequeueAll",
      "GamePlaySound",
      "GameEntityPlaySound",
      "GameEntityPlaySoundLoop",
      "GameUnsetPostFxParameter",
      "StreamingSetCustomPhaseDurations",
      "StreamingForceNewVoting",
      "StreamingSetVotingEnabled",
      "GameSetCameraPos",
      "GuiDestroy",
      "GuiStartFrame",
      "GuiOptionsAdd",
      "GuiOptionsRemove",
      "GuiOptionsClear",
      "GuiOptionsAddForNextWidget",
      "GuiColorSetForNextWidget",
      "GuiZSet",
      "GuiZSetForNextWidget",
      "GuiIdPush",
      "GuiIdPushString",
      "GuiIdPop",
      "GuiAnimateBegin",
      "GuiAnimateEnd",
      "GuiAnimateAlphaFadeIn",
      "GuiAnimateScaleIn",
      "GuiText",
      "GuiImage",
      "GuiImageNinePiece",
      "GuiBeginAutoBox",
      "GuiEndAutoBoxNinePiece",
      "GuiTooltip",
      "GuiBeginScrollContainer",
      "GuiEndScrollContainer",
      "GuiLayoutBeginHorizontal",
      "GuiLayoutBeginVertical",
      "GuiLayoutAddHorizontalSpacing",
      "GuiLayoutAddVerticalSpacing",
      "GuiLayoutEnd",
      "GuiLayoutBeginLayer",
      "GuiLayoutEndLayer",
      "DebugEnableTrailerMode",
      "Debug_SaveTestPlayer",
      "EntityConvertToMaterial",
      "ConvertEverythingToGold",
      "ConvertMaterialEverywhere",
      "ConvertMaterialOnAreaInstantly",
      "LoadRagdoll",
      "DEBUG_GameReset",
      "ComponentSetValueVector2",
      "ComponentSetValueValueRange",
      "ComponentSetValueValueRangeInt",
      "ComponentSetMetaCustom",
      "ComponentObjectSetValue",
      "PhysicsBodyIDGetBodyAABB",
      "BiomeMapLoad",

      // TODO: implement this?
      "ModRegisterAudioEventMappings",
      "ModMaterialsFileAdd",
      "ModRegisterMusicBank",
      "BiomeSetValue",
      "BiomeGetValue",
      "BiomeObjectSetValue",
      "BiomeVegetationSetValue",
      "BiomeMaterialSetValue",
      "BiomeMaterialGetValue",
    ]
  },
  { // 0, 0
    fn: () => [0, 0],
    list: [
      "PhysicsBodyIDGetWorldCenter",
      "PhysicsBodyIDGetDamping",
      "InputGetJoystickAnalogStick",
      "EntityGetHotspot",
      "ComponentGetValueVector2",
      "GuiGetScreenDimensions",
      "GuiGetTextDimensions",
      "GuiGetImageDimensions",
      "GameGetVelocityCompVelocity",
      "EntityGetFirstHitboxCenter",
      "FindFreePositionForBody",
      "DEBUG_GetMouseWorld",
      "SpawnApparition",
      "GetGameEffectLoadTo",
      "InputGetMousePosOnScreen",
      "PhysicsGetComponentVelocity",
      "GameGetCameraPos",
      // Could be implemented later:
      "PhysicsVecToGameVec",
      "GameVecToPhysicsVec",
      "PhysicsPosToGamePos",
      "GamePosToPhysicsPos"
    ]
  },
  { // false, 0, 0
    fn: () => [false, 0, 0],
    list: [
      "Raytrace",
      "RaytraceSurfaces",
      "RaytraceSurfacesAndLiquiform",
      "RaytracePlatforms",
    ]
  },
  { // [0, 0, 0, 0, 0, 0]
    fn: () => [0, 0, 0, 0, 0, 0],
    list: [
      "PhysicsComponentGetTransform",
      "PhysicsBodyIDGetTransform",
    ]
  }
];
