import { profilerEnabled } from "./profiler";

let cache: string = "";
let cacheProfiler: string = "";

export function getLuaPlaceholder() {
  if (!profilerEnabled && cache) return cache;
  if (profilerEnabled && cacheProfiler) return cacheProfiler;

  const lua = _blankFunctions.map(
    ({ ret, list }) => list.map(
      (fn) => profilerEnabled
        ? `function ${fn}() __perf_immediate("${fn}") return ${ret} end`
        : `function ${fn}() return ${ret} end`
    )
  ).flat().join("\n");

  if (profilerEnabled) {
    cacheProfiler = lua;
  } else {
    cache = lua;
  }

  return lua;
}

const _blankFunctions = [
  { ret: "0",
    list: [
      "ModImageGetPixel",
      "ComponentGetValue2",
      "ComponentObjectGetValue2",
      "PhysicsBodyIDGetGravityScale",
      "InputGetJoystickAnalogButton",
      "GameGetFogOfWar",
      "GameGetFogOfWarBilinear",
      "GameGetSkyVisibility",
      "ComponentGetValueInt",
      "ComponentGetValueFloat",
      "EntityLoad",
      "EntityLoadEndGameItem",
      "EntityCreateNew",
      "EntityAddComponent",
      "EntityGetParent",
      "EntityGetRootEntity",
      "EntityGetClosest",
      "EntityGetClosestWithTag",
      "EntityGetWithName",
      "EntitiesGetMaxID",
      "EntityAddComponent2",
      "ComponentGetVectorSize",
      "ComponentGetEntity",
      "GetUpdatedEntityID",
      "GetUpdatedComponentID",
      "SpawnStash",
      "RemoveMaterialInventoryMaterial",
      "GetMaterialInventoryMainMaterial",
      "GameGetWorldStateEntity",
      "GameGetPlayerStatsEntity",
      "GameGetOrbCountAllTime",
      "GameGetOrbCountThisRun",
      "CellFactory_GetType",
      "EntityGetWandCapacity",
      "GameGetGameEffect",
      "GameGetGameEffectCount",
      "LoadGameEffectEntityTo",
      "GameGetPotionColorUint",
      "StringToHerdId",
      "GetHerdRelation",
      "EntityGetHerdRelation",
      "EntityGetHerdRelationSafe",
      "CreateItemActionEntity",
      "BiomeMapGetVerticalPositionInsideBiome",
      "PhysicsAddBodyImage",
      "PhysicsAddBodyCreateBox",
      "PhysicsAddJoint",
      "PhysicsGetComponentAngularVelocity",
      "StreamingGetVotingCycleDurationFrames",
      "GuiSlider",
      "GetDailyPracticeRunSeed"
    ]
  },
  { ret: "false",
    list: [
      "ModImageDoesExist",
      "GameIsBetaBuild",
      "DebugGetIsDevBuild",
      "GameSetFogOfWar",
      "InputIsJoystickButtonDown",
      "InputIsJoystickButtonJustDown",
      "InputIsJoystickConnected",
      "ComponentGetValueBool",
      "EntityHasTag",
      "GameIsIntroPlaying",
      "ComponentGetIsEnabled",
      "GameGetIsGamepadConnected",
      "GameGetOrbCollectedThisRun",
      "GameGetOrbCollectedAllTime",
      "GameIsInventoryOpen",
      "RemovePixelSceneBackgroundSprite",
      "InputIsKeyDown",
      "InputIsKeyJustDown",
      "InputIsKeyJustUp",
      "InputIsMouseButtonDown",
      "InputIsMouseButtonJustDown",
      "InputIsMouseButtonJustUp",
      "IsPlayer",
      "IsInvisible",
      "GameIsDailyRun",
      "GameIsDailyRunOrDailyPracticeRun",
      "StreamingGetIsConnected",
      "StreamingGetSettingsGhostsNamedAfterViewers",
      "GameGetIsTrailerModeEnabled",
    ]
  },
  { ret: '""',
    list: [
      "ModImageWhoSetContent",
      "ComponentGetMetaCustom",
      "ComponentObjectGetValue",
      "EntityGetName",
      "ComponentGetTypeName",
      "CellFactory_GetName",
      "CellFactory_GetUIName",
      "HerdIdToString",
      "GetRandomActionWithType",
      "GetRandomAction",
      "BiomeMapGetName",
      "StreamingGetConnectedChannelName",
      "StreamingGetRandomViewerName",
      "GuiTextInput",
      "DebugBiomeMapGetFilename",
    ]
  },
  { ret: "{}",
    list: [
      "GuiCreate",
      "ModMaterialFilesGet", // TODO
      "PhysicsBodyIDGetFromEntity",
      "PhysicsBodyIDQueryBodies",
      "EntityGetAllComponents",
      "EntityGetInRadius",
      "EntityGetAllChildren",
      "EntityGetInRadiusWithTag",
      "EntityGetComponent",
      "CellFactory_GetAllLiquids",
      "CellFactory_GetAllSands",
      "CellFactory_GetAllGases",
      "CellFactory_GetAllFires",
      "CellFactory_GetAllSolids",
      "CellFactory_HasTag",
      "CellFactory_GetTags",
      "GameGetAllInventoryItems",
      "PolymorphTableGet",
    ]
  },
  { ret: "nil",
    list: [
      "ModImageSetPixel",
      "GuiTextCentered",
      "GameSetPostFxTextureParameter",
      "GameUnsetPostFxTextureParameter",
      "VerletApplyDirectionalForce",
      "VerletApplyCircularForce",
      "RegisterStreamingEvent",
      "PhysicsBodyIDSetGravityScale",
      "PhysicsBodyIDSetDamping",
      "PhysicsBodyIDApplyTorque",
      "PhysicsBodyIDApplyForce",
      "PhysicsBodyIDApplyLinearImpulse",
      "PhysicsBodyIDSetTransform",
      "PhysicsComponentSetTransform",
      "GenomeSetHerdId",
      "EntityRemoveStainStatusEffect",
      "GameSetPostFxParameter",
      "ModDevGenerateSpriteUVsForDirectory",
      "EntityLoadCameraBound",
      "EntityLoadToEntity",
      "EntitySave",
      "EntityKill",
      "EntityRemoveComponent",
      "EntityGetFirstComponent",
      "EntityGetComponentIncludingDisabled",
      "EntityGetFirstComponentIncludingDisabled",
      "EntitySetTransform",
      "EntityApplyTransform",
      "EntityAddChild",
      "EntityRemoveFromParent",
      "EntitySetComponentsWithTagEnabled",
      "EntitySetComponentIsEnabled",
      "EntitySetName",
      "EntityGetTags",
      "EntityAddTag",
      "EntityRemoveTag",
      "EntityGetFilename",
      "ComponentAddTag",
      "ComponentRemoveTag",
      "ComponentHasTag",
      "ComponentGetTags",
      "ComponentGetValue",
      "ComponentSetValue",
      "ComponentSetValue2",
      "ComponentObjectSetValue2",
      "ComponentGetVectorValue",
      "ComponentGetVector",
      "ComponentGetMembers",
      "ComponentObjectGetMembers",
      "RegisterSpawnFunction",
      "SpawnActionItem",
      "LoadEntityToStash",
      "AddMaterialInventoryMaterial",
      "GameScreenshake",
      "GameOnCompleted",
      "GameGiveAchievement",
      "GameDoEnding2",
      "BiomeMapLoad_KeepPlayer",
      "GameClearOrbsFoundThisRun",
      "GameSetCameraFree",
      "GameRegenItemAction",
      "GameRegenItemActionsInContainer",
      "GameRegenItemActionsInPlayer",
      "GameKillInventoryItem",
      "GamePickUpInventoryItem",
      "GameDropAllItems",
      "GameDropPlayerInventoryItems",
      "GameDestroyInventoryItems",
      "GameTriggerGameOver",
      "LoadPixelScene",
      "LoadBackgroundSprite",
      "RemovePixelSceneBackgroundSprites",
      "GameCreateCosmeticParticle",
      "GameCreateParticle",
      "GameCreateSpriteForXFrames",
      "GameShootProjectile",
      "EntityInflictDamage",
      "EntityIngestMaterial",
      "EntityRemoveIngestionStatusEffect",
      "EntityAddRandomStains",
      "EntitySetDamageFromMaterial",
      "EntityRefreshSprite",
      "GamePlayAnimation",
      "SetPlayerSpawnLocation",
      "UnlockItem",
      "PolymorphTableAddEntity",
      "PolymorphTableRemoveEntity",
      "PolymorphTableSet",
      "SessionNumbersSave",
      "AutosaveDisable",
      "StatsBiomeReset",
      "StatsLogPlayerKill",
      "GameEmitRainParticles",
      "GameCutThroughWorldVertical",
      "PhysicsApplyForce",
      "PhysicsApplyTorque",
      "PhysicsApplyTorqueToComponent",
      "PhysicsApplyForceOnArea",
      "PhysicsRemoveJoints",
      "PhysicsSetStatic",
      "PhysicsBody2InitFromComponents",
      "LooseChunk",
      "GameTriggerMusicEvent",
      "GameTriggerMusicCue",
      "GameTriggerMusicFadeOutAndDequeueAll",
      "GamePlaySound",
      "GameEntityPlaySound",
      "GameEntityPlaySoundLoop",
      "GameUnsetPostFxParameter",
      "StreamingSetCustomPhaseDurations",
      "StreamingForceNewVoting",
      "StreamingSetVotingEnabled",
      "GameSetCameraPos",
      "GuiDestroy",
      "GuiStartFrame",
      "GuiOptionsAdd",
      "GuiOptionsRemove",
      "GuiOptionsClear",
      "GuiOptionsAddForNextWidget",
      "GuiColorSetForNextWidget",
      "GuiZSet",
      "GuiZSetForNextWidget",
      "GuiIdPush",
      "GuiIdPushString",
      "GuiIdPop",
      "GuiAnimateBegin",
      "GuiAnimateEnd",
      "GuiAnimateAlphaFadeIn",
      "GuiAnimateScaleIn",
      "GuiText",
      "GuiImage",
      "GuiImageNinePiece",
      "GuiBeginAutoBox",
      "GuiEndAutoBoxNinePiece",
      "GuiTooltip",
      "GuiBeginScrollContainer",
      "GuiEndScrollContainer",
      "GuiLayoutBeginHorizontal",
      "GuiLayoutBeginVertical",
      "GuiLayoutAddHorizontalSpacing",
      "GuiLayoutAddVerticalSpacing",
      "GuiLayoutEnd",
      "GuiLayoutBeginLayer",
      "GuiLayoutEndLayer",
      "DebugEnableTrailerMode",
      "Debug_SaveTestPlayer",
      "EntityConvertToMaterial",
      "ConvertEverythingToGold",
      "ConvertMaterialEverywhere",
      "ConvertMaterialOnAreaInstantly",
      "LoadRagdoll",
      "DEBUG_GameReset",
      "ComponentSetValueVector2",
      "ComponentSetValueValueRange",
      "ComponentSetValueValueRangeInt",
      "ComponentSetMetaCustom",
      "ComponentObjectSetValue",
      "PhysicsBodyIDGetBodyAABB",
      "BiomeMapLoad",

      // TODO: implement this?
      "ModRegisterAudioEventMappings",
      "ModMaterialsFileAdd",
      "ModRegisterMusicBank",
      "BiomeSetValue",
      "BiomeGetValue",
      "BiomeObjectSetValue",
      "BiomeVegetationSetValue",
      "BiomeMaterialSetValue",
      "BiomeMaterialGetValue",
    ]
  },
  { ret: "true",
    list: [
      "EntityGetIsAlive",
      "DoesWorldExistAt",
      "GameIsModeFullyDeterministic"
    ]
  },
  { ret: "0, 0",
    list: [
      "PhysicsBodyIDGetWorldCenter",
      "PhysicsBodyIDGetDamping",
      "InputGetJoystickAnalogStick",
      "EntityGetHotspot",
      "ComponentGetValueVector2",
      "GuiGetScreenDimensions",
      "GuiGetTextDimensions",
      "GuiGetImageDimensions",
      "GameGetVelocityCompVelocity",
      "EntityGetFirstHitboxCenter",
      "FindFreePositionForBody",
      "DEBUG_GetMouseWorld",
      "SpawnApparition",
      "GetGameEffectLoadTo",
      "InputGetMousePosOnScreen",
      "PhysicsGetComponentVelocity",
      "GameGetCameraPos",
      // Could be implemented later:
      "PhysicsVecToGameVec",
      "GameVecToPhysicsVec",
      "PhysicsPosToGamePos",
      "GamePosToPhysicsPos"
    ]
  },
  { ret: "false, false",
    list: [
      "GuiImageButton",
      "GuiButton"
    ]
  },
  { ret: "0, 0, 0",
    list: [
      "EntityGetClosestWormAttractor",
      "ModImageMakeEditable",
      "ModImageIdFromFilename"
    ]
  },
  { ret: "false, 0, 0",
    list: [
      "Raytrace",
      "RaytraceSurfaces",
      "RaytraceSurfacesAndLiquiform",
      "RaytracePlatforms",
    ]
  },
  { ret: "0, 0, 0, 0",
    list: ["EntityGetClosestWormDetractor"]
  },
  { ret: "0, 0, 1, 1",
    list: ["GameGetCameraBounds"]
  },
  { ret: "0, 0, 0, 1, 1",
    list: ["EntityGetTransform"]
  },
  { ret: "false, 0, 0, 0",
    list: ["GetSurfaceNormal"]
  },
  { ret: "0, 0, 0, 0, 0, 0",
    list: [
      "PhysicsComponentGetTransform",
      "PhysicsBodyIDGetTransform",
    ]
  },
  { ret: "false, false, false, 0, 0, 1, 1, 0, 0, 1, 1",
    list: ["GuiGetPreviousWidgetInfo"]
  },
  { ret: "{ 0 }",
    list: ["EntityGetWithTag"]
  }
];

export const PLACEHOLDER_FUNCS = new Set(_blankFunctions.map((x) => x.list).flat());
